name: Tester

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Image
      run: docker build -t jarrettgaither/liatriowebapp .

    - name: Run Container
      run: docker run -p 80:80 --name container1 jarrettgaither/liatriowebapp

    - name: Wait for start
      run: sleep 5s
    
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master

    - name: Stop Container
      run: docker stop container1
