name: Tester

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Image
      run: docker build -t jarrettgaither/liatriowebapp .
  container-tester:
      runs-on: ubuntu-latest
      container: 
        image: jarrettgaither/liatriowebapp
      steps:
         - name: run tests
           uses: liatrio/github-actions/apprentice-action@master

         - name: Stop Container
           run: docker stop container1
